python/portale_sport/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.index.home'),
    url(r'^accounts/login/*$', 'core.views.auth.login_view'),
    url(r'^accounts/logout/$', 'core.views.auth.logout_view'),
    url(r'^accounts/register/$', 'core.views.auth.register'),
    url(r'^list/partita/$', 'core.views.index.list_partita'),
    url(r'^add/partita/$', 'core.views.index.add_partita'),
    # url(r'^portale_sport/', include('portale_sport.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

python/portale_sport/core/models/partita.py
from django.db import models
from sport import Sport
from struttura import Struttura

class Partita(models.Model):
    name = models.CharField(max_length=50)
    tipo = models.ForeignKey(Sport)
    giorno = models.DateField()
    ora = models.TimeField()
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        app_label = "core"
        verbose_name_plural = "Partita"

python/portale_sport/core/models/sport.py
from django.db import models

class Sport(models.Model):
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        app_label = "core"

python/portale_sport/core/models/struttura.py
from django.db import models
from sport import Sport

class Struttura(models.Model):
    name = models.CharField(max_length=50)
    sport = models.ForeignKey(Sport)
    indirizzo = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        app_label = "core"
        verbose_name_plural = "Strutture"

python/portale_sport/core/forms/login_form.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Nome utente", max_length = 30)
    passwd = forms.CharField(label = "Password", widget = forms.PasswordInput)
    next = forms.CharField(max_length = 255)

python/portale_sport/core/forms/partita_form.py
from django.forms import ModelForm
from core.models.partita import Partita

class PartitaForm(ModelForm):
    
    class Meta:
        model = Partita

python/portale_sport/core/forms/register_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(label = "Nome", max_length = 30)
    last_name = forms.CharField(label = "Cognome", max_length = 30)
    email = forms.CharField(label = "Email", max_length = 75)
    
    def save(self, commit = True):
        user = super(RegisterForm, self).save(commit = False)
        user.set_password(self.cleaned_data["password1"])
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

python/portale_sport/core/views/index.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required

from core.models.partita import Partita
from core.forms.partita_form import PartitaForm

@login_required
def home(request):
    pageContext = {"title": "Pagina principale"}
    return render_to_response("home.html", pageContext, RequestContext(request))

@login_required
def list_partita(request):
    pageContext = {"title": "Prossime partite"}
    pageContext.update({"list": Partita.objects.all()})
    return render_to_response("list.html", pageContext, RequestContext(request))

@login_required
def add_partita(request):
    pageContext = {"title": "Nuova partita"}
    if request.method == "POST":
        form = PartitaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/list/partita/")
    else:
        form = PartitaForm()
    pageContext.update({"form": form})
    return render_to_response("form.html", pageContext, RequestContext(request))

python/portale_sport/core/templates/base.html
{% load profile %}

<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8" />
    <title>foolimpik</title>
    <meta name="description" content="Portale per organizzare gratuitamente partite tra amici per ogni genere di sport" />
    <meta name="keywords" content="calcio, calcetto, calcetto a 5, calcetto a 7, amici, social, tennis, basket, palla a volo, palla a canestro, volley, soccer, organizzare, partite, partitelle, partita, partitella, campo, campi, campetto, tornei, torneo, sfida, sfide, coppa, coppe, medaglie, giocatori, atleti, giocatore, atleta, statistiche, portale, web, facebook, sport, allenamento, forum" />
    
    <link rel="stylesheet" href="/static/css/base.css" type="text/css" />
    <link rel="stylesheet" href="/static/css/custom-theme/jquery-ui-1.8.15.custom.css" type="text/css" />
    <link rel="stylesheet" href="/static/css/tipTip.css" type="text/css" />
    {% block mycss %}{% endblock %}

    <script src="/static/js/jquery-1.6.2.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-ui-1.8.15.custom.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
    <script src="/static/js/jquery.tipTip.minified.js" type="text/javascript"></script>
    {% block myjs %}{% endblock %}
    
    <script type="text/javascript">
      $(document).ready(function() {
          $(".title_tooltip").tipTip();
          $("#id_giorno").datepicker({dateFormat:"yy-mm-dd"});
          $("#id_ora").timepicker({});
      });
      
      {% block script %}{% endblock %}
    </script>
  </head>

  <body>
    <div class="header">
      <a href="/"><span>foolimpik</span></a>
    </div>
    <div class="content">
      <div class="left">
	{% user_profile %}
	<a href="/"><span class="link_menu">Pagina principale</span></a>
	
	{% if user.is_authenticated %}
	<a href="/add/partita/"><span class="link_menu">Partite</span></a>
	{% endif %}
	<a href="#"><span class="link_menu">Classifiche</span></a>
	<a href="#"><span class="link_menu">Forum</span></a>
	{% if user.is_authenticated %}
	<a href="#"><span class="link_menu">Messaggi</span></a>
	<a href="#"><span class="link_menu">Strutture</span></a>
	{% endif %}
	<a href="#"><span class="link_menu">Chi siamo</span></a>
      </div>
      <div class="center">{% block content %}{% endblock %}</div>
      <div class="right">
	prova
      </div>
    </div>
    <div class="footer">
    </div>
  </body>

</html>

python/portale_sport/core/templates/form.html
{% extends "base.html" %}

{% block content %}

<h1>{{ title }}</h1>

<form method="POST" action=".">
  {% csrf_token %}
  {% for field in form %}
  <div class="field {% if field.errors %}error{% endif %}">{{ field.label_tag }}{{ field }}{{ field.errors }}</div>
  {% endfor %}
  <div class="buttons">
    <input class="btn_full" type="submit" value="Invia" />
    <input type="reset" value="Cancella" />
  </div>
</form>

{% endblock %}

python/portale_sport/core/templates/home.html
{% extends "base.html" %}

{% block content %}

<h1>{{ title }}</h1>

<p>prova</p>
<p>......</p>
<p>prova</p>
<p>......</p>
<p>prova</p>

{% endblock %}

python/portale_sport/core/templates/list.html
{% extends "base.html" %}

{% block content %}

<h1>{{ title }}</h1>

<div class="listelem">
  {% for e in list %}
  <div class="elem">
    {{ e }}
  </div>
  {% endfor %}
</div>

{% endblock %}

python/portale_sport/core/templates/login.html
{% extends "base.html" %}

{% block content %}

<h1>Accesso al sito</h1>

<form method="POST" action="/accounts/login/">
  {% csrf_token %}
  <input type="hidden" id="next" name="next" value="{{ next }}" />
  
  <div class="field {% if form.username.errors %}error{% else %}{% if err%}error{% endif %}{% endif %}">{{ form.username.label_tag }}{{ form.username }}{{ form.username.errors }}</div>
  <div class="field {% if form.passwd.errors %}error{% else %}{% if err%}error{% endif %}{% endif %}">{{ form.passwd.label_tag }}{{ form.passwd }}{{ form.passwd.errors }}</div>
  
  {% if err %}
  <div class="field">
    <ul class="errorlist"><li>Nome utente e password non corrispondono o sono errati.</li></ul>
  </div>
  {% endif %}
  
  <div><p>Non sei ancora registrato? <a class="link" href="/accounts/register/"><span>clicca qui</span></a></p></div>
  <div class="buttons">
    <input class="btn_full" type="submit" value="Login" />
    <input type="reset" value="Cancella" />
  </div>
  
</form>

{% endblock %}

python/portale_sport/core/templates/profile.html
<div class="profile">
  <div class="pavatar">
    <img src="/static/profile/{{ user.username }}.jpg" alt="avatar" width="48" height="48" />
  </div>
  <div class="puser">
    <a class="title_tooltip link" href="/profile/{{ user.username }}/" title="Clicca per visualizzare<br/>il profilo utente"><span class="username">{{ user.first_name }}</span></a>
    <a class="link" href="/accounts/logout/"><span>Esci</span></a>
  </div>
</div>